# Generated by Django 4.2 on 2023-04-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp_m',
            name='user_o',
        ),
    ]
