# Generated by Django 4.2 on 2023-04-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_otp_m_user_o'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='gpa',
            field=models.ImageField(db_column='gpa Picture', null=True, upload_to='gpa'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gpa_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='point1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='point2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='point3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='point4',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
